global_seed: 17

# Run Name
run_name:  # If left blank, will be read from env var $RUN_NAME

model:
  name: hf_causal_lm
  pretrained: true
  pretrained_model_name_or_path: meta-llama/Llama-2-7b-hf
  config_overrides:
    max_seq_len: ${max_seq_len}
    attn_config:
      attn_impl: triton
      # Set this to `true` if using `train_loader.dataset.packing_ratio` below
      attn_uses_sequence_id: false

# Tokenizer
tokenizer:
  name: meta-llama/Llama-2-7b-chat-hf
  kwargs:
    model_max_length: ${max_seq_len}
    trust_remote_code: true


# FSDP configuration
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  flatten_parameters: true
  forward_prefetch: true
  backward_prefetch: BACKWARD_PRE
  limit_all_gathers: true
  activation_checkpointing: false
  sync_module_states: true
  forward_sync: true
  use_orig_params: false
  backward_sync: true
  ignored_modules: []
  state_dict_type: FULL_STATE_DICT
  sync_module_states: true
  activation_checkpointing_reentrant: false
  cpu_offload: false
  min_params: 0
  param_persistence: SELECTIVE

# Tensor parallelism configuration
tp_config:
  enabled: true
  strategy: "tensor_parallel"
  size: 4  # Using tensor parallelism of size 4 on 16 GPUs

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 50ba  # add some warmup though, seems to help with MPT
  alpha_f: 0.1
  base_lr: 1.0e-6
  min_lr: 0.0

optimizer:
  # Based on Dolly
  name: decoupled_adamw
  lr: 5.0e-6
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-8
  weight_decay: 0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 2ep  # 2-3 epochs seems like the sweet spot
eval_interval: 1ep
# eval_subset_num_batches: -1
eval_first: true
global_train_batch_size: 48  # somewhere in the 6-8 * numgpus range seems good

# System
seed: ${global_seed}
device_eval_batch_size: 8
device_train_microbatch_size: 8
# device_train_microbatch_size: auto
precision: amp_bf16


# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

ppo:
  kl_coeff: 0.1  # Controls how much the policy can deviate from the reference model
  temperature: 0.7 # Controls randomness in generation (higher = more random)
  top_p: 1.1  # Nucleus sampling parameter (1.0 = disabled)
  top_k: -1 # Top-k sampling parameter (-1 = disabled)
  max_response_tokens: 1024 # Maximum number of tokens to generate in each response
  generations_per_sample: 4
  episodes_per_iteration: 64 # Number of episodes to collect per iteration for training
  num_iterations: 1000



