max_seq_len: 1024 
model:
  name: hf_causal_lm
  #init_device: mixed
  pretrained: true
  pretrained_model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct
  use_flash_attention_2: false

# load_path: oci://mosaicml-internal-integration-testing/elastic_resumption_1_to_2_node/ep0-ba10

# Tokenizer
tokenizer:
  name: Qwen/Qwen2.5-0.5B-Instruct
  kwargs:
    model_max_length: ${max_seq_len}
    trust_remote_code: true

# FSDP configuration
fsdp:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  flatten_parameters: true
  forward_prefetch: true
  backward_prefetch: BACKWARD_PRE
  limit_all_gathers: true
  activation_checkpointing: false
  sync_module_states: true
  forward_sync: true
  use_orig_params: false
  backward_sync: true
  ignored_modules: []
  state_dict_type: FULL_STATE_DICT
  activation_checkpointing_reentrant: false
  cpu_offload: false
  min_params: 0
  param_persistence: SELECTIVE

tp:
  strategy: "ffn"
  tensor_parallel_degree: 8

vllm:
  enabled: true
  strategy: "tensor_parallel"
  inference_tp_size: 2  # Using tensor parallelism of size 4 on 16 GPUs
  enable_sleep_mode: false  # Turn it on for GPU. CPU does not suport sleep mode

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 50ba  # add some warmup though, seems to help with MPT
  alpha_f: 0.1
  base_lr: 1.0e-6
  min_lr: 0.0

optimizer:
  name: decoupled_adamw
  lr: 5.0e-6
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-8
  weight_decay: 0

train_loader:
  name: ppo
  dataset:
    split: train
    max_seq_len: ${max_seq_len}
    allow_pad_trimming: false
    decoder_only_format: true
    shuffle: true
  drop_last: true
  num_workers: 8
  pin_memory: false
  prefetch_factor: 2
  persistent_workers: true
  timeout: 0

eval_interval: 25
eval_first: true
global_train_batch_size: 48  # somewhere in the 6-8 * numgpus range seems good

# System
seed: 17
device_eval_batch_size: 8
device_train_microbatch_size: 8
# device_train_microbatch_size: auto
precision: amp_bf16
dist_timeout: 600

# Logging
loggers:
  mlflow:
    tags:
      group: test
    experiment_name: /Users/xiaohan.zhang@databricks.com/ppo_test
  progress_bar: false
  log_to_console: true

ppo:
  kl_coeff: 0.1  # Controls how much the policy can deviate from the reference model
  temperature: 0.7 # Controls randomness in generation (higher = more random)
  top_p: 0.9  # Nucleus sampling parameter (1.0 = disabled)
  top_k: -1 # Top-k sampling parameter (-1 = disabled)
  max_response_tokens: 1024 # Maximum number of tokens to generate in each response
  generations_per_sample: 4
  episodes_per_iteration: 64 # Number of episodes to collect per iteration for training
  num_iterations: 1000



